# Generated by Django 5.2 on 2025-05-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=100, unique=True)),
                ("group1", models.CharField(blank=True, max_length=100)),
                ("sub_group1_1", models.CharField(blank=True, max_length=100)),
                ("drr", models.FloatField(default=0)),
                ("required_doh", models.PositiveIntegerField(default=0)),
                ("seasonality", models.CharField(blank=True, max_length=50)),
                ("lifecycle_status", models.CharField(blank=True, max_length=50)),
                ("current_inventory", models.IntegerField(default=0)),
                ("grn_inventory", models.IntegerField(default=0)),
                ("buffer_inventory", models.IntegerField(default=0)),
            ],
        ),
    ]
